### ISSUE TITLE
I'm trying to add another code. But it doesn't seem to work. 

### ISSUE THREAD

**Issue by UnknownUW** [kabirsingh2004/JUGNU-MUSIC#10]
Hi, I was hoping to get some help here on what I should do in this code. I'm trying to add another code which is called together, it contains youtube together and many other games. But when I try to use this code, it doesn't seem to do anything with the code. However, it does prompt me with an error code which is the image that you will see. 
![Screenshot 2022-03-27 070349](https://user-images.githubusercontent.com/91180068/160278535-c0f24767-c248-4659-9b39-73701331f0ac.png)

// // slash command

const { Command } = require("reconlx");
const emoji = require("../../settings/emoji.json");
const embed = require("../../settings/embed.json");
const config = require("../../settings/config.json");

module.exports = new Command({
  // options
  name: "together",
  description: `You can either play a game or watch youtube together in your voice chat!`,
  userPermissions: [],
  botPermissions: [],
  category: "Music",
  cooldown: 10,
  // command start
  run: async ({ client, interaction, args, prefix }) => {
    // Code
//     const Command = require("../structures/command.js");
// const { MessageActionRow, MessageSelectMenu } = require('discord.js');

		const row = new MessageActionRow()
		.addComponents(
			new MessageSelectMenu()
				.setCustomId('together')
				.setPlaceholder('Choose an activity')
				.setMinValues(1)
				.setMaxValues(1)
				.addOptions([
					{
						label: 'YouTube',
						value: '880218394199220334'
					},
					{
						label: 'Poker',
						value: '755827207812677713'
					},
					{
						label: 'Chess',
						value: '832012774040141894'
					},
					{
						label: 'Checkers',
						value: '832013003968348200'
					},
					{
						label: 'Betrayal',
						value: '773336526917861400'
					},
					{
						label: 'Fishington',
						value: '814288819477020702'
					},
					{
						label: 'Words Snack',
						value: '879863976006127627'
					},
					{
						label: 'Doodle Crew',
						value: '878067389634314250'
					},
					{
						label: 'Spellcast',
						value: '852509694341283871'
					},
					{
						label: 'Awkword',
						value: '879863881349087252'
					},
					{
						label: 'Letter Tile',
						value: '879863686565621790'
					}
				]),
		);
		message.reply({ 
			embeds: [
				{
					author: {
						name: "Discord Together",
						iconURL: message.guild.iconURL()
					},
					description: `Choose an activity below!`,
					footer: {
						text: 'You must be in a voice channel and on a desktop to use this feature.'
					},
					color: 0x44b868
				}
			],
			components: [row]
		});
	}
});

// message command aka prefix cmd
const { Message, Client } = require("discord.js");
// const emoji = require("../../settings/emoji.json");
// const embed = require("../../settings/embed.json");
// const config = require("../../settings/config.json");

module.exports = {
  name: "together",
  aliases: [""],
  description: `You can either play a game or watch youtube together in your voice chat!`,
  userPermissions: [],
  botPermissions: [],
  category: "Music",
  cooldown: 10,

  /**
   *
   * @param {Client} client
   * @param {Message} message
   * @param {String[]} args
   */
  run: async (client, message, args , prefix) => {
    // code
    const row = new MessageActionRow()
		.addComponents(
			new MessageSelectMenu()
				.setCustomId('together')
				.setPlaceholder('Choose an activity')
				.setMinValues(1)
				.setMaxValues(1)
				.addOptions([
					{
						label: 'YouTube',
						value: '880218394199220334'
					},
					{
						label: 'Poker',
						value: '755827207812677713'
					},
					{
						label: 'Chess',
						value: '832012774040141894'
					},
					{
						label: 'Checkers',
						value: '832013003968348200'
					},
					{
						label: 'Betrayal',
						value: '773336526917861400'
					},
					{
						label: 'Fishington',
						value: '814288819477020702'
					},
					{
						label: 'Words Snack',
						value: '879863976006127627'
					},
					{
						label: 'Doodle Crew',
						value: '878067389634314250'
					},
					{
						label: 'Spellcast',
						value: '852509694341283871'
					},
					{
						label: 'Awkword',
						value: '879863881349087252'
					},
					{
						label: 'Letter Tile',
						value: '879863686565621790'
					}
				]),
		);

**Comment by CoolMusic1** [comment]
Hello User ,
U will get errors as u can add another bot code with Jugnu / Cool Music Codes

Tip : U can make 2 repl with same bot token to do it 
Thanks

**Comment by Discobotdevlolhehe** [comment]
if it wont work, just add a different project to the same bot

**Comment by CoolMusic1** [comment]
yes

**Comment by CoolMusic1** [comment]
if u still have issue open new
Thanks
