### ISSUE TITLE
bug "Someone disconnected me from channel" on /stop

### ISSUE THREAD

**Issue by dotxyzcf** [kabirsingh2004/JUGNU-MUSIC#12]
![grafik](https://user-images.githubusercontent.com/92203938/160334517-57c3c4ca-3979-45c7-bf37-a53b62c0ba02.png)

**Comment by CoolMusic1** [comment]
We know u can edit the command and write Someone Disconnected Me , Song has ended or someone stoped the music 
Tip :- Use /setup Command
Thanks
