### ISSUE TITLE
seek dont work

### ISSUE THREAD

**Issue by dotxyzcf** [kabirsingh2004/JUGNU-MUSIC#13]
if i use /seek the bot does seek on me but thinks in infinite and disconnects after seeking... (only if the seek amount is 100 or higher btw the song is 3 hours long)

![grafik](https://user-images.githubusercontent.com/92203938/160468759-d2ed10d9-542b-4a7f-a8b3-65ab0e6f7e87.png)

**Comment by CoolMusic1** [comment]
we fixed it update ur code with latest
