### ISSUE TITLE
after searching and selecting a song the bot doesnt changes the message that he added it to the queue but the song got added to queue

### ISSUE THREAD

**Issue by dotxyzcf** [kabirsingh2004/JUGNU-MUSIC#14]
![grafik](https://user-images.githubusercontent.com/92203938/160469981-e46a795f-4aa9-4422-ae29-465f6d802148.png)

![grafik](https://user-images.githubusercontent.com/92203938/160470113-d5e51965-25c2-4dc5-a495-d6d087df582b.png)

**Comment by CoolMusic1** [comment]
It takes time to update
