### ISSUE TITLE
Crashing after seeking

### ISSUE THREAD

**Issue by dotxyzcf** [kabirsingh2004/JUGNU-MUSIC#18]
![grafik](https://user-images.githubusercontent.com/92203938/160869937-65975e2d-2615-4cdd-af34-3295b50892a0.png)

Optional:

Add fseek command to forward seek (incl buttons to seek +10 secs and - 10 secs!)
add a syntax like /seek 1m = 1 min, 1h = 1hour etc makes it users easyer to seek!

**Comment by CoolMusic1** [comment]
i fixed the issue but Kabu again changed Ahhh.... Dm Kabu

**Comment by CoolMusic1** [comment]
Use this and tell me if it fixes

const { Command } = require("reconlx");
const ee = require("../../settings/embed.json");
const config = require("../../settings/config.json");
const emoji = require("../../settings/emoji.json");
const player = require("../../handlers/player");
const { check_dj } = require("../../handlers/functions");

module.exports = new Command({
  // options
  name: "seek",
  description: ` set seek current song`,
  userPermissions: [""],
  botPermissions: ["CONNECT"],
  category: "Music",
  cooldown: 5,
  DJ: true,
  options: [
    {
      name: "amount",
      description: `Give seek amount in number`,
      type: "NUMBER",
      required: true,
    },
  ],
  // command start
  run: async ({ client, interaction, args, prefix }) => {
    // Code
    let channel = interaction.member.voice.channel;
    let queue = await player.getQueue(interaction.guild.id);
    if (!channel) {
      return interaction.followUp(
        `** ${emoji.ERROR} You Need to Join Voice Channel first **`
      );
    } else if (
      interaction.guild.me.voice.channel &&
      !interaction.guild.me.voice.channel.equals(channel)
    ) {
      return interaction.followUp(
        `** ${emoji.ERROR} You Need to Join __My__ Voice Channel **`
      );
    } else if (interaction.guild.me.voice.serverMute) {
      return interaction.followUp(
        `** ${emoji.ERROR} I am Muted in Voice Channel , unmute me first **`
      );
    } else if (!queue) {
      return interaction.followUp(`** ${emoji.ERROR} Nothing Playing Now **`);
    } else if (check_dj(client, interaction.member, queue.songs[0])) {
      return interaction.followUp(
        `** ${emoji.ERROR} You are Not DJ and also not Song Requester **`
      );
    } else {
      let seeksong = interaction.options.getNumber("amount")
                if (seeksong > queue.songs[0].duration || seeksong < 0) return interaction.reply({
                    embeds: [
                        new MessageEmbed().setColor(ee.wrongcolor).setTitle(`${client.allEmojis.x} **The Seek Position must be between \`0\` and \`${Queue.songs[0].duration}\`!**`)
                    ] });
await queue.seek(seeksong);
    }
  },
});

**Comment by CoolMusic1** [comment]
use this and tell me if it fixed 
`const { Command } = require("reconlx");
const ee = require("../../settings/embed.json");
const config = require("../../settings/config.json");
const emoji = require("../../settings/emoji.json");
const player = require("../../handlers/player");
const { check_dj } = require("../../handlers/functions");

module.exports = new Command({
  // options
  name: "seek",
  description: ` set seek current song`,
  userPermissions: [""],
  botPermissions: ["CONNECT"],
  category: "Music",
  cooldown: 5,
  DJ: true,
  options: [
    {
      name: "amount",
      description: `Give seek amount in number`,
      type: "NUMBER",
      required: true,
    },
  ],
  // command start
  run: async ({ client, interaction, args, prefix }) => {
    // Code
    let channel = interaction.member.voice.channel;
    let queue = await player.getQueue(interaction.guild.id);
    if (!channel) {
      return interaction.followUp(
        `** ${emoji.ERROR} You Need to Join Voice Channel first **`
      );
    } else if (
      interaction.guild.me.voice.channel &&
      !interaction.guild.me.voice.channel.equals(channel)
    ) {
      return interaction.followUp(
        `** ${emoji.ERROR} You Need to Join __My__ Voice Channel **`
      );
    } else if (interaction.guild.me.voice.serverMute) {
      return interaction.followUp(
        `** ${emoji.ERROR} I am Muted in Voice Channel , unmute me first **`
      );
    } else if (!queue) {
      return interaction.followUp(`** ${emoji.ERROR} Nothing Playing Now **`);
    } else if (check_dj(client, interaction.member, queue.songs[0])) {
      return interaction.followUp(
        `** ${emoji.ERROR} You are Not DJ and also not Song Requester **`
      );
    } else {
      let seeksong = interaction.options.getNumber("amount")
                if (seeksong > queue.songs[0].duration || seeksong < 0) return interaction.reply({
                    embeds: [
                        new MessageEmbed().setColor(ee.wrongcolor).setTitle(`${client.allEmojis.x} **The Seek Position must be between \`0\` and \`${Queue.songs[0].duration}\`!**`)
                    ] });
await queue.seek(seeksong);
    }
  },
});
`

**Comment by CoolMusic1** [comment]
use this and tell me if it fixed
```const { Command } = require("reconlx");
const ee = require("../../settings/embed.json");
const config = require("../../settings/config.json");
const emoji = require("../../settings/emoji.json");
const player = require("../../handlers/player");
const { check_dj } = require("../../handlers/functions");

module.exports = new Command({
  // options
  name: "seek",
  description: `set seek current song`,
  userPermissions: [""],
  botPermissions: ["CONNECT"],
  category: "Music",
  cooldown: 5,
  DJ: true,
  options: [
    {
      name: "amount",
      description: `Give seek amount in number`,
      type: "NUMBER",
      required: true,
    },
  ],
  // command start
  run: async ({ client, interaction, args, prefix }) => {
    // Code
    let channel = interaction.member.voice.channel;
    let queue = await player.getQueue(interaction.guild.id);
    if (!channel) {
      return interaction.followUp(
        `** ${emoji.ERROR} You Need to Join Voice Channel first **`
      );
    } else if (
      interaction.guild.me.voice.channel &&
      !interaction.guild.me.voice.channel.equals(channel)
    ) {
      return interaction.followUp(
        `** ${emoji.ERROR} You Need to Join __My__ Voice Channel **`
      );
    } else if (interaction.guild.me.voice.serverMute) {
      return interaction.followUp(
        `** ${emoji.ERROR} I am Muted in Voice Channel , unmute me first **`
      );
    } else if (!queue) {
      return interaction.followUp(`** ${emoji.ERROR} Nothing Playing Now **`);
    } else if (check_dj(client, interaction.member, queue.songs[0])) {
      return interaction.followUp(
        `** ${emoji.ERROR} You are Not DJ and also not Song Requester **`
      );
    } else {
      let seeksong = interaction.options.getNumber("amount")
                if (seeksong > queue.songs[0].duration || seeksong < 0) return interaction.reply({
                    embeds: [
                        new MessageEmbed().setColor(ee.wrongcolor).setTitle(`${client.allEmojis.x} **The Seek Position must be between \`0\` and \`${Queue.songs[0].duration}\`!**`)
                    ] });
await queue.seek(seeksong);
    }
  },
});
```

**Comment by CoolMusic1** [comment]
u said the bot crash before

**Comment by dotxyzcf** [comment]
on kabus version the bots craches after seeking. on yours its seeking but dont send a output like "i seeked to your location"!

**Comment by CoolMusic1** [comment]
ohk i will fix it
