### ISSUE TITLE
Bot not starting on local

### ISSUE THREAD

**Issue by Rocky-pup** [kabirsingh2004/JUGNU-MUSIC#27]
Bot is not loading commands and events at all on local machine
Os: Win 10

![image](https://user-images.githubusercontent.com/83218418/178134804-753af57e-c069-49b4-9ede-d13f7cbce442.png)

**Comment by kabirsingh2004** [comment]
you follow tutorial carefully ?

**Comment by Rocky-pup** [comment]
I think yes

**Comment by Rocky-pup** [comment]
Download, unzip, npm i, npm i node, node index.js

**Comment by kabirsingh2004** [comment]
> 

no follow again 
first update node verison then install all package

**Comment by Rocky-pup** [comment]
Is 16.15.1 is not enough? I tried to re-install 2 or 3 times, not helping

**Comment by CoolMusic1** [comment]
use node V17

**Comment by Rocky-pup** [comment]
Ok
