### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Amased** [kabirsingh2004/JUGNU-MUSIC#36]
Hello, I have a encountered a problem, when I try to use filters, it gives me an error in the console saying "queue.filters.join is not a function"
I have attached an image of it, please help me with it, thanks for the help!
![image](https://user-images.githubusercontent.com/73810498/189382740-71e53f60-ff0f-43b7-914b-5e735008dcf3.png)

**Comment by CoolMusic1** [comment]
have u used the latest code ?

**Comment by Amased** [comment]
Yes I have tried using the latest code, but it still appears
