### ISSUE TITLE
bot filter command makes bot stop working

### ISSUE THREAD

**Issue by jmggithub1** [kabirsingh2004/JUGNU-MUSIC#39]
whenever I put a filter command the bot just stops and the bot in replit stops running

**Comment by Amased** [comment]
> whenever I put a filter command the bot just stops and the bot in replit stops running

Actually I've had the same problem, I had also made a bug comment like this on here lol

**Comment by CoolMusic1** [comment]
are u using the latest package ?

**Comment by jmggithub1** [comment]
I am using the latest. It just says queue.filters.join is not a function.
