### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by Maccroe** [kabirsingh2004/JUGNU-MUSIC#49]
**_Lyrics is not working, It just showing No Lyrics found for song.****_**

**Comment by kabirsingh2004** [comment]
it provide only lyrics of some songs

**Comment by rif4815** [comment]
When I started the bot it’s working fine but after sometimes like 4-5 hr later bot stop responding.  And  I checked my hosting it’s working properly. Also music takes so long to start sometimes..
