### ISSUE TITLE
I am getting a 429 error

### ISSUE THREAD

**Issue by LukeMedeiros916** [kabirsingh2004/JUGNU-MUSIC#5]
I am getting a 429 error, this I know is a rate limit error. Is there anyway to get around this with the YouTube "kookie" section in the .json file? Is there anyway to run this with proxies?

**Comment by BRAVO68WEB** [comment]
Try changing VPS host
Or Try different API Key

**Comment by kabirsingh2004** [comment]
watch this

https://www.youtube.com/watch?v=9bZGT9frKLw
