### ISSUE TITLE
eror'ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by alixtron0** [kabirsingh2004/JUGNU-MUSIC#53]
![image](https://user-images.githubusercontent.com/106485382/218324940-126d8dc7-d237-4be3-a90d-d19337863778.png)

**Comment by alixtron0** [comment]
and this error is on Ubuntu vps

**Comment by Discobotdevlolhehe** [comment]
npm i better-sqlite@latest usually does the trick
