### ISSUE TITLE
Hello Kabir Sir Everytime I’m Getting this Error! Please Fix this 🙏 

### ISSUE THREAD

**Issue by Marks100K** [kabirsingh2004/JUGNU-MUSIC#58]
**Found a Error...**
PlayingError: Status code: 429
Id: NVXgPsK_eTw
Name: Top 100 NoCopyRightSounds | Best of
NCS | Most Viewed Songs | The Best of All Time | 2022 | 6H

**Comment by kabirsingh2004** [comment]
rate limit error
