### ISSUE TITLE
Simple issue help

### ISSUE THREAD

**Issue by Murat1Na** [kabirsingh2004/JUGNU-MUSIC#67]
Hey, the bot stays in the voice channel even when 24/7 is off, can you tell me how to fix this pls

**Comment by kabirsingh2004** [comment]
okie i will check how many minutes it stay in vc ?

**Comment by Murat1Na** [comment]
> okie i will check how many minutes it stay in vc ?

it stays without leaving at all

**Comment by bugsum** [comment]
Should be fixed in the next version!

**Comment by kabirsingh2004** [comment]
fixed now check
