### ISSUE TITLE
Interaction Create in setup mode

### ISSUE THREAD

**Issue by nenewnnn** [kabirsingh2004/JUGNU-MUSIC#7]
Why is it that when I change the voice channel and I type in the title of the song, I am not given an alert. looks like "InteractionCreate" doesn't work. InteractionCreate in Player_Handler.js

**Comment by CoolMusic1** [comment]
it have issue we will fix it

**Comment by nenewnnn** [comment]
![unknown](https://user-images.githubusercontent.com/100553047/159676068-2aa31f65-dec5-4168-b169-b7400a0f1c5d.png)

**Comment by nenewnnn** [comment]
> it have issue we will fix it or u can see now we updated the code

if i'm not in VC, and i'm text in setup mode. This error appear.

**Comment by CoolMusic1** [comment]
We know as we have not added this thing that if someone text something in the setup channel without connect on vc bot will not delete the msg of the user
