### ISSUE TITLE
the bot stop playing the song after 1 minute

### ISSUE THREAD

**Issue by 3ziz0011** [kabirsingh2004/JUGNU-MUSIC#8]

**Comment by CoolMusic1** [comment]
where u host the bot ?
replit / VPS ?

**Comment by 3ziz0011** [comment]
i host the bot in my pc

im using visual studio code

**Comment by CautionGamer** [comment]
> i host the bot in my pc
> 
> im using visual studio code

Please Contract In Our Support Server :- discord.gg/tbd
