### ISSUE TITLE
Not edit  Buttons

### ISSUE THREAD

**Issue by DDK0001** [kabirsingh2004/JUGNU-MUSIC#9]
When create new channel using "/setup",gives this error & don't edit buttons "pause to resume" & not send song resumed message.
p.s:- 395:20 is in you given command line.
![Player_Handler js - D_D_K - Visual Studio Code 3_24_2022 10_35_49 AM](https://user-images.githubusercontent.com/102277507/159846428-626404c3-66a3-4303-b471-ecf43ae6ce47.png)
.

**Comment by CoolMusic1** [comment]
ok we will fix it

**Comment by kabirsingh2004** [comment]
it give error when msg is undefined

**Comment by DDK0001** [comment]
I didn't delete msg,how could it undefined.

**Comment by kabirsingh2004** [comment]
>>> sometimes bot can't cache message

**Comment by CoolMusic1** [comment]
Do it again
